AWSTemplateFormatVersion: '2010-09-09'
Description: Basic Minecraft Server Setup on EC2 with S3 Bucket for Mods

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair to enable SSH access

Resources:

  MinecraftEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  MinecraftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Minecraft and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MinecraftS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "minecraft-mods-${AWS::AccountId}-${AWS::Region}"

  MinecraftS3AccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt MinecraftS3Bucket.Arn
                  - !Sub "${MinecraftS3Bucket.Arn}/*"

  MinecraftInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MinecraftS3AccessRole

  MinecraftInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.large
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MinecraftSecurityGroup
      IamInstanceProfile: !Ref MinecraftInstanceProfile
      ImageId: ami-0fe972392d04329e1 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install Java 21 (Azul Zulu)
          yum install java-17-amazon-corretto
          wget -qO - https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg
          echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" > /etc/apt/sources.list.d/zulu.list
          apt-get update
          apt-get install -y zulu21-jdk unzip curl

          # Install AWS CLI v2
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install


          # Create mc folder
          mkdir -p /opt/minecraft/

          # Download Fabric installer (you can automate running it later)
          wget https://meta.fabricmc.net/v2/versions/loader/1.19.1/0.14.21/1.0.3/server/jar -O /opt/minecraft/fabric-installer.jar

          # Run Fabric installer
          cd /opt/minecraft
          java -jar fabric-installer.jar
          sed -i 's/eula=false/eula=true/' eula.txt

          wget https://github.com/Snakiestgoose/minecraft-aws/blob/Snakiestgoose-patch-1/mods/TreeChop-1.19.2-fabric-0.17.6.jar -O /opt/minecraft/mods/TreeChop-1.19.2-fabric-0.17.6.jar
          
          java -jar fabric-installer.jar

          #aws s3 cp s3://minecraft-mods-${AWS::AccountId}-${AWS::Region}/modfile.jar /opt/minecraft/mods/

  MinecraftEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MinecraftEIP.AllocationId
      InstanceId: !Ref MinecraftInstance

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaFullAccessToEC2AndS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - ec2:*
                Resource: !GetAtt MinecraftServerInstance.Arn
              - Effect: Allow
                Action: 
                  - s3:*
                Resource: !GetAtt MinecraftBucket.Arn
              - Effect: Allow
                Action:
                  - s3:*
                Resource: !Sub "${MinecraftBucket.Arn}/*"

  MinecraftLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Code:
        ZipFile: |
          def handler(event, context):
              return {"statusCode": 200, "body": "Hello from Lambda!"}
          
Outputs:
  InstancePublicIP:
    Description: Public IP of Minecraft server
    Value: !GetAtt MinecraftInstance.PublicIp

  MinecraftModsBucket:
    Description: S3 bucket for storing Minecraft mods
    Value: !Ref MinecraftS3Bucket
